services:
  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-cpp-cuda
    ports:
      - "8082:8082"
    volumes:
      - ./llamacpp/models:/models
      - ./llamacpp/llama_models_config.ini:/llama_models_config.ini
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      --port 8082
      --models-dir /models
      --models-preset /llama_models_config.ini
      --host 0.0.0.0
      --parallel 2

  server:
    build:
      context: ./papers-server
    container_name: papers-server
    environment:
      - SERVER_IP=0.0.0.0
      - LM_CONFIG_FILE=lm-config.yaml
    depends_on:
      - llamacpp
    volumes:
      - "./lm-config.yaml:/app/lm-config.yaml:ro"
      - "./common/utils.py:/app/utils.py:ro"
    restart: on-failure

  client:
    image: jupyter/base-notebook:latest
    container_name: papers-client
    ports:
      - 8888:8888
    depends_on:
      - server
      - llamacpp
    environment:
      - SERVER_URL=http://server:8000
      - LM_CONFIG_FILE=../lm-config.yaml
    volumes:
      - "./paper-export-client:/home/jovyan/work/paper-export-client"
      - "./lm-config.yaml:/home/jovyan/work/lm-config.yaml:ro"
      - "./common:/home/jovyan/work/app/common:rw"
    restart: on-failure


volumes:
  llamacpp_data: