main_language_model:
  provider: openai
  model: NVIDIA-Nemotron-3-Nano-4B-GGUF
  base_url: http://llamacpp:8082/v1
  key_env_var: OPENAI_API_KEY
  key: llamacpp

main_embedding_model:
  provider: openai
  model: embeddinggemma-300m-qat-GGUF
  base_url: http://llamacpp:8082/v1
  key_env_var: OPENAI_API_KEY
  key: llamacpp
