[*]
load-on-startup = false

[gemma-4-E4B-it-GGUF]
# numeric value
n-gpu-layers = 32
# context size
c = 32768
# only load this one when it starts
load-on-startup = true
# "infinite" context
context-shift = true

[embeddinggemma-300m-qat-GGUF]
# embedding model
embeddings = true
# can fill in GPU
n-gpu-layers = -1
# input batch size
b = 2048
ub = 2048
# only load this one when it starts
load-on-startup = true
