[*]
load-on-startup = false

[embeddinggemma-300m-qat-GGUF]
# embedding model
embeddings = true
# can fill in GPU
n-gpu-layers = -1
# input batch size
b = 2048
ub = 2048
# only load this one when it starts
load-on-startup = true
